let graphGesture=null,graphSource='',graphSelection='',graphUndo=null;
function ensureScenes(){const a=s();a.scenes??=[];a.sceneMigration??={};let migrated=false;for(const [world,mappings] of Object.entries(a.foundryBindings||{})){if(a.sceneMigration[world])continue;a.sceneMigration[world]=true;migrated=true;for(const [location,m] of Object.entries(mappings)){if(!m.scene||a.scenes.some(x=>x.location===location&&x.foundryScenes?.[world]===m.scene))continue;a.scenes.push({id:uid(),name:loc(location)?.name||'Scena',location,gm:'',player:'',foundryScenes:{[world]:m.scene},status:'available'});}}if(migrated)persist();}
function connectLocations(from,to){if(from===to||!loc(from)||!loc(to))return false;if(s().links.some(([a,b])=>a===from&&b===to||a===to&&b===from))return false;s().links.push([from,to]);return true;}
function graphSnapshot(){return {scenario:s().id,links:structuredClone(s().links),positions:s().locations.map(x=>({id:x.id,x:x.x,y:x.y}))};}
function graphRestore(snapshot){if(!snapshot||snapshot.scenario!==s().id)return;s().links=snapshot.links.filter(([a,b])=>loc(a)&&loc(b));for(const p of snapshot.positions){const l=loc(p.id);if(l){l.x=p.x;l.y=p.y;}}}
function graphLines(){return s().links.map(([a,b],i)=>{const x=loc(a),y=loc(b);return x&&y?`<g><line class="graph-edge" data-edge="${i}" x1="${x.x}" y1="${x.y}" x2="${y.x}" y2="${y.y}"/><line class="graph-edge-hit" data-edge="${i}" x1="${x.x}" y1="${x.y}" x2="${y.x}" y2="${y.y}"/></g>`:''}).join('');}
function graphMarkup(){const a=s();return `<div class="title-row"><h1>Lokacje i połączenia</h1>${b('+ Lokacja','add-locations','','primary')}</div><p class="sub">Przeciągnij kartę, aby ją ustawić. Przeciągnij okrągły uchwyt do drugiej lokacji, aby je połączyć.</p><div class="graph-toolbar row"><span id="graph-help" role="status">Kliknij połączenie, aby je usunąć. Dwuklik na lokacji otwiera edycję.</span><button type="button" data-graph="undo" ${graphUndo?.scenario===a.id?'':'disabled'}>Cofnij ostatnią zmianę</button></div><div class="graph-board" id="graph-board"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Połączenia lokacji"><g id="graph-lines">${graphLines()}</g><line id="graph-preview" hidden x1="0" y1="0" x2="0" y2="0"/></svg>${a.locations.map(l=>`<div class="graph-node ${l.id===graphSelection?'selected':''} ${l.id===a.current?'current':''}" data-node="${esc(l.id)}" style="left:${l.x}%;top:${l.y}%"><button type="button" class="graph-drag" data-node-drag="${esc(l.id)}" aria-label="Przesuń lokację ${esc(l.name)}">${esc(l.name)}</button><button type="button" class="graph-port ${l.id===graphSource?'armed':''}" data-port="${esc(l.id)}" aria-label="Połącz lokację ${esc(l.name)}" title="Przeciągnij do lokacji lub kliknij dwa uchwyty">●</button></div>`).join('')}</div><p class="map-caption">Schemat bez skali. Połączenia są dwukierunkowe. Pozycje i połączenia zapisują się automatycznie. Możesz też połączyć lokacje klikając kolejno dwa uchwyty.</p><div class="cards">${a.locations.map(l=>`<article class="card"><h2>${esc(l.name)}</h2><p>${esc(l.player)}</p><p class="muted">Połączone: ${esc(a.links.filter(e=>e.includes(l.id)).map(e=>loc(e.find(id=>id!==l.id))?.name).filter(Boolean).join(', ')||'Brak')}</p>${source(l)}<div class="row">${b('Prowadź tutaj','move',l.id)}${b('Edytuj','edit-location',l.id)}<button type="button" data-custom="location-scene" data-location="${esc(l.id)}">+ Scena tutaj</button></div></article>`).join('')}</div>`;}
function sceneFoundryId(scene){return scene.foundryScenes?.[foundryBridge.catalog?.world]||'';}
function sceneCard(scene,compact=false){const c=foundryBridge.catalog,id=sceneFoundryId(scene),exists=c?.scenes.some(x=>x.id===id);return `<article class="card scene-card"><div class="title-row"><h3>${esc(scene.name)}</h3><span class="tag">${scene.status==='played'?'ROZEGRANA':'SCENA'}</span></div><p class="muted">${esc(loc(scene.location)?.name||'Dowolna lokacja')}</p>${compact?'':`<p>${esc(scene.player)}</p><details><summary>Notatki MG</summary><div class="secret">${esc(scene.gm)}</div></details><label>Scena Foundry — zapis automatyczny<select data-scene-binding="${esc(scene.id)}" ${c?'':'disabled'}>${sel([['','Bez powiązania'],...(c?.scenes||[]).map(x=>[x.id,x.name]),...(id&&!exists?[[id,'Scena niedostępna w tym świecie']]:[])],id)}</select></label>`}<div class="row"><button type="button" class="primary" data-custom="activate-scene" data-scene="${esc(scene.id)}" ${exists?'':'disabled'}>${c?.activeScene===id&&id?'Scena aktywna':'Pokaż graczom'}</button>${b('Edytuj','edit-scenes',scene.id,'small')}<button type="button" data-custom="scene-status" data-scene="${esc(scene.id)}" class="small">${scene.status==='played'?'Przywróć':'Oznacz rozegraną'}</button></div>${!c?'<p class="source">Połącz z Foundry, aby przypisać i pokazać scenę.</p>':!exists?'<p class="source">Wybierz scenę Foundry w zakładce Sceny.</p>':''}</article>`;}
function scenesMarkup(){return `<div class="title-row"><h1>Sceny Twojego scenariusza</h1>${b('+ Scena','add-scenes','','primary')}</div><p class="sub">Lokacja to miejsce. Scena to przygotowana sytuacja — do jednego miejsca możesz dodać wiele scen.</p><div class="notice">${esc(foundryBridge.status)}. Powiązanie z Foundry zapisuje się po wyborze; „Pokaż graczom” aktywuje scenę jednym kliknięciem.</div><div class="cards">${s().scenes.map(x=>sceneCard(x)).join('')||empty('Dodaj pierwszą scenę: nadaj nazwę, wybierz lokację i przygotuj opis. Sceny możesz tworzyć także bez Foundry.')}</div>`;}
fields.scenes=[['name','Nazwa sceny'],['location','Lokacja','location'],['player','Opis dla graczy','text'],['gm','Przebieg / notatki MG','text']];
foundryPanel=function(){const c=foundryBridge.catalog,m=foundryMapping()[s().current]||{};return `<section class="panel" id="foundry-panel"><h2>Foundry VTT</h2><p class="muted" role="status">${esc(foundryBridge.status)}</p>${c?`<p class="source">Sceny przypisujesz raz w zakładce Sceny. Na dashboardzie użyj „Pokaż graczom”.</p><label>Powiązany dziennik — zapis automatyczny<select data-custom-journal>${sel([['','Bez powiązania'],...c.journals.map(x=>[x.id,x.name])],m.journal||'')}</select></label><div class="row"><button type="button" data-fv="chat">Opis lokacji na czat</button><button type="button" data-fv="handout">Handout z opisu</button><button type="button" data-fv="preview" ${m.journal?'':'disabled'}>Podgląd dziennika MG</button><button type="button" data-fv="journal" ${m.journal?'':'disabled'}>Pokaż dziennik graczom</button><button type="button" data-fv="refresh">Odśwież listę</button></div>`:'<p>Otwórz Companion przez moduł w sesji MG, aby sterować Foundry. Własne lokacje i sceny możesz przygotować lokalnie.</p>'}</section>`;};
tabs.splice(2,0,['scenes','▣  Sceny']);
const customRenderBase=render;
render=function(){if(graphGesture){if(view==='map'&&graphGesture.snapshot.scenario===s().id)return;cancelGraphGesture();}ensureScenes();customRenderBase();if(view==='map')$('#content').innerHTML=graphMarkup();if(view==='scenes')$('#content').innerHTML=scenesMarkup();if(view==='session'){const current=s().scenes.filter(x=>x.location===s().current||x.location==='*');$('#content').insertAdjacentHTML('afterbegin',`<section class="panel"><div class="title-row"><h2>Sceny w tej lokacji</h2><button type="button" data-custom="location-scene" data-location="${esc(s().current)}">+ Scena</button></div><div class="cards">${current.map(x=>sceneCard(x,true)).join('')||'<p class="muted">Dodaj własną scenę albo przygotuj ją w zakładce Sceny.</p>'}</div></section>`);const panel=$('#foundry-panel');if(panel){const wrap=document.createElement('details');wrap.className='foundry-tools';const summary=document.createElement('summary');summary.textContent='Foundry · opisy, handouty i ustawienia';wrap.append(summary);panel.before(wrap);wrap.append(panel);}}};
function redrawGraph(){const group=$('#graph-lines');if(group)group.innerHTML=graphLines();}
function cancelGraphGesture(){const g=graphGesture;if(!g)return;graphGesture=null;graphRestore(g.snapshot);try{g.target.releasePointerCapture(g.pointer);}catch{}graphSource='';}
function graphPoint(e){const r=$('#graph-board')?.getBoundingClientRect();if(!r||r.width<=0||r.height<=0)return null;return {x:Math.max(8,Math.min(92,(e.clientX-r.left)/r.width*100)),y:Math.max(8,Math.min(92,(e.clientY-r.top)/r.height*100))};}
document.addEventListener('pointerdown',e=>{const drag=e.target.closest('[data-node-drag]'),port=e.target.closest('[data-port]');if((!drag&&!port)||e.button!==0)return;const id=drag?.dataset.nodeDrag||port.dataset.port;graphGesture={id,mode:port?'connect':'move',startX:e.clientX,startY:e.clientY,snapshot:graphSnapshot(),moved:false,pointer:e.pointerId,target:e.target};try{e.target.setPointerCapture(e.pointerId);}catch{graphGesture=null;return;}e.preventDefault();});
document.addEventListener('pointermove',e=>{const g=graphGesture;if(!g||g.pointer!==e.pointerId)return;if(Math.hypot(e.clientX-g.startX,e.clientY-g.startY)<5&&!g.moved)return;const p=graphPoint(e),l=loc(g.id);if(!p||!l){cancelGraphGesture();render();return;}g.moved=true;if(g.mode==='move'){l.x=p.x;l.y=p.y;const node=g.target.closest('[data-node]');node.style.left=p.x+'%';node.style.top=p.y+'%';redrawGraph();}else{const preview=$('#graph-preview');preview.removeAttribute('hidden');for(const [k,v]of Object.entries({x1:l.x,y1:l.y,x2:p.x,y2:p.y}))preview.setAttribute(k,v);}});
document.addEventListener('pointerup',e=>{const g=graphGesture;if(!g||g.pointer!==e.pointerId)return;graphGesture=null;try{g.target.releasePointerCapture(e.pointerId);}catch{}if(g.mode==='move'){graphSelection=g.id;if(g.moved){graphUndo=g.snapshot;changed('Przesunięto lokację: '+loc(g.id).name);}else{document.querySelectorAll('[data-node]').forEach(node=>node.classList.toggle('selected',node.dataset.node===g.id));}return}let to=g.moved?document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]')?.dataset.node:null;if(!g.moved){if(graphSource&&graphSource!==g.id){to=g.id;g.id=graphSource;graphSource='';}else{graphSource=graphSource===g.id?'':g.id;render();return;}}if(to&&connectLocations(g.id,to)){graphUndo=g.snapshot;graphSource='';changed('Połączono lokacje: '+loc(g.id).name+' ↔ '+loc(to).name);}else render();});
document.addEventListener('pointercancel',()=>{cancelGraphGesture();render();});
document.addEventListener('lostpointercapture',e=>{if(graphGesture?.pointer===e.pointerId){cancelGraphGesture();render();}});
window.addEventListener('blur',()=>{if(graphGesture){cancelGraphGesture();render();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(graphGesture)graphRestore(graphGesture.snapshot);graphGesture=null;graphSource='';if(view==='map')render();}if((e.key==='Enter'||e.key===' ')&&e.target.dataset.port){e.preventDefault();const id=e.target.dataset.port;if(graphSource&&graphSource!==id){const before=graphSnapshot();if(connectLocations(graphSource,id)){graphUndo=before;changed('Połączono lokacje');}graphSource='';}else graphSource=id;render();}});
document.addEventListener('dblclick',e=>{const node=e.target.closest('[data-node-drag]');if(node)edit('locations',node.dataset.nodeDrag);});
document.addEventListener('click',async e=>{const edge=e.target.closest('[data-edge]');if(edge){graphUndo=graphSnapshot();s().links.splice(Number(edge.dataset.edge),1);changed('Usunięto połączenie lokacji');return}if(e.target.closest('[data-graph="undo"]')){const previous=graphUndo;graphUndo=null;graphRestore(previous);changed('Cofnięto zmianę schematu');return}const button=e.target.closest('[data-custom]');if(!button)return;const action=button.dataset.custom;if(action==='location-scene'){edit('scenes',null,{location:button.dataset.location});return}const scene=s().scenes.find(x=>x.id===button.dataset.scene);if(!scene)return;if(action==='scene-status'){scene.status=scene.status==='played'?'available':'played';changed('Status sceny: '+scene.name);return}if(action==='activate-scene'){if(foundryBridge.busy)return;foundryBridge.busy=true;button.disabled=true;try{await foundryRequest('activateScene',{id:sceneFoundryId(scene)});if(loc(scene.location))s().current=scene.location;foundryBridge.catalog.activeScene=sceneFoundryId(scene);foundryBridge.status='Aktywna scena: '+scene.name;changed('Foundry: pokazano scenę '+scene.name);}catch(err){foundryBridge.status=err.message;render();}finally{foundryBridge.busy=false;}}});
document.addEventListener('change',e=>{const id=e.target.dataset.sceneBinding;if(!id||!foundryBridge.catalog)return;const scene=s().scenes.find(x=>x.id===id);scene.foundryScenes??={};scene.foundryScenes[foundryBridge.catalog.world]=e.target.value;persist();render();});
document.addEventListener('change',e=>{if(e.target.matches('[data-custom-journal]')){const m=foundryMapping();m[s().current]={...(m[s().current]||{}),journal:e.target.value};persist();render();}});
render();


