/* The Foundry module hosts this same app in a GM-owned frame. No server token. */
const foundryBridge={port:null,catalog:null,pending:new Map(),status:'Tryb lokalny — uruchom panel przez moduł Foundry',busy:false};
function foundryRequest(action,payload={}) {
  if(!foundryBridge.port)return Promise.reject(Error('Brak połączenia z Foundry. Otwórz Companion przyciskiem modułu w sesji MG.'));
  const id=uid();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{foundryBridge.pending.delete(id);reject(Error('Brak potwierdzenia z Foundry. Sprawdź rezultat na stole przed ponowieniem działania.'));},15000);foundryBridge.pending.set(id,{resolve,reject,timer});foundryBridge.port.postMessage({id,action,payload});});
}
window.addEventListener('message',e=>{
  if(window.parent===window||e.source!==window.parent||e.origin!==window.location.origin||e.data?.protocol!=='kult-gm-companion-v1'||e.data?.type!=='connected'||!e.ports[0])return;
  foundryBridge.port?.close();foundryBridge.port=e.ports[0];foundryBridge.catalog=e.data.catalog;foundryBridge.status='Połączono z Foundry';
  foundryBridge.port.onmessage=e=>{const m=e.data;if(m?.type==='catalog'){foundryBridge.catalog=m.catalog;render();return}const p=foundryBridge.pending.get(m?.id);if(!p)return;clearTimeout(p.timer);foundryBridge.pending.delete(m.id);m.ok?p.resolve(m.result):p.reject(Error(m.error||'Błąd Foundry'));};foundryBridge.port.start();render();
});
function foundryMapping(){const world=foundryBridge.catalog?.world||'offline';s().foundryBindings??={};s().foundryBindings[world]??={};return s().foundryBindings[world];}
function foundryPanel(){const c=foundryBridge.catalog,l=loc(s().current),m=foundryMapping()[l.id]||{};
  return `<div class="panel" id="foundry-panel"><div class="title-row"><h2>Foundry VTT</h2><span class="tag">${c?'POŁĄCZONO':'LOKALNIE'}</span></div><p class="muted" role="status">${esc(foundryBridge.status)}${c?' · '+esc(c.world)+' · '+esc(c.user):''}</p>${c?`<div class="row"><label>Scena dla „${esc(l.name)}”<select id="fv-scene">${sel([['','Bez powiązania'],...c.scenes.map(x=>[x.id,x.name])],m.scene||'')}</select></label><label>Handout / wpis dziennika<select id="fv-journal">${sel([['','Bez powiązania'],...c.journals.map(x=>[x.id,x.name])],m.journal||'')}</select></label><button type="button" data-fv="save">Zapisz powiązania</button><button type="button" data-fv="refresh">Odśwież listę</button></div><p class="source">Aktywna scena: ${esc(c.scenes.find(x=>x.id===c.activeScene)?.name||'Brak')}. Wybór lokacji w Companion nie przełącza stołu, dopóki nie klikniesz przycisku.</p><div class="row"><button type="button" data-fv="activate" ${m.scene?'':'disabled'}>Pokaż scenę graczom</button><button type="button" data-fv="chat">Wyślij opis lokacji na czat</button><button type="button" data-fv="handout">Utwórz handout z opisu</button><button type="button" data-fv="preview" ${m.journal?'':'disabled'}>Podgląd dziennika MG</button><button type="button" data-fv="journal" ${m.journal?'':'disabled'}>Pokaż powiązany dziennik</button></div><p class="source">Opis i nowy handout zawierają wyłącznie pole „Opis dla graczy”. Powiązany dziennik jest pokazywany w całości — najpierw sprawdź jego treść.</p>`:`<p>Rozpakuj moduł <strong>kult-gm-companion</strong> do Data/modules, włącz go w świecie Foundry i kliknij „KULT Companion” jako MG. W tym panelu pojawi się połączenie.</p><p class="source">Przenieś obecną sesję: Kopia sesji → Import w panelu modułu. Zapis w Foundry jest osobny dla świata i konta MG.</p>`}</div>`;
}
const renderBase=render;
render=function(){renderBase();if(view==='session'||view==='settings')$('#content').insertAdjacentHTML('afterbegin',foundryPanel());if(view==='session'||view==='clues'){for(const button of document.querySelectorAll('[data-action="copy-clue"]')){const extra=document.createElement('button');extra.type='button';extra.className='small';extra.textContent='Wyślij wskazówkę do Foundry';extra.dataset.fv='clue';extra.dataset.clue=button.dataset.id;button.after(extra);}}};
function foundryPreview(title,body,action,payload,onSuccess){const d=$('#editor');d.innerHTML=`<h2>${esc(title)}</h2><div class="player" style="max-height:45vh;overflow:auto;margin-bottom:20px">${esc(body)}</div><p class="muted">Ten materiał trafi do graczy po wysłaniu.</p><div class="row"><button type="button" id="fv-confirm" class="primary">Wyślij do Foundry</button><button type="button" data-action="close">Anuluj</button></div>`;d.showModal();$('#fv-confirm').onclick=async()=>{const button=$('#fv-confirm');button.disabled=true;try{const result=await foundryRequest(action,payload);d.close();onSuccess?.();foundryBridge.status=result.warning||'Foundry potwierdziło działanie';changed('Foundry: '+title,'play');}catch(err){foundryBridge.status=err.message;button.disabled=false;notify(err.message);}};}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-fv]');if(!el)return;const action=el.dataset.fv,l=loc(s().current),mapping=foundryMapping()[l.id]||{};
  if(!foundryBridge.port){notify('Otwórz Companion przez moduł Foundry w zalogowanej sesji MG.');return}
  if(action==='save'){foundryMapping()[l.id]={scene:$('#fv-scene').value,journal:$('#fv-journal').value};changed('Powiązano lokację z Foundry: '+l.name);return}
  if(action==='chat'||action==='handout'){if(!l.player?.trim()){notify('Lokacja nie ma opisu dla graczy.');return}foundryPreview(action==='chat'?'Opis lokacji na czat':'Nowy handout: '+l.name,l.player,action,{title:l.name,text:l.player});return}
  if(action==='clue'){const clue=s().clues.find(x=>x.id===el.dataset.clue);if(!clue?.player?.trim()){notify('Uzupełnij opis wskazówki dla graczy.');return}foundryPreview('Wskazówka: '+clue.name,clue.player,'chat',{title:clue.name,text:clue.player},()=>{clue.status='revealed';});return}
  if(action==='journal'){const j=foundryBridge.catalog.journals.find(x=>x.id===mapping.journal);if(!j){notify('Wybierz i zapisz dziennik.');return}foundryPreview('Pokaż dziennik: '+j.name,'Cały istniejący wpis „'+j.name+'” zostanie pokazany wszystkim połączonym graczom, również bez dotychczasowych uprawnień. Sprawdź wcześniej przyciskiem „Podgląd dziennika MG”, czy nie zawiera sekretów.','showJournal',{id:j.id});return}
  if(foundryBridge.busy)return;foundryBridge.busy=true;el.disabled=true;
  try{if(action==='refresh')foundryBridge.catalog=await foundryRequest('catalog');if(action==='activate'){if(!mapping.scene)throw Error('Najpierw zapisz powiązanie sceny.');await foundryRequest('activateScene',{id:mapping.scene});foundryBridge.catalog=await foundryRequest('catalog');log('Foundry: aktywowano scenę dla '+l.name,'play');persist();}if(action==='preview'){await foundryRequest('previewJournal',{id:mapping.journal});window.parent.postMessage({protocol:'kult-gm-companion-v1',type:'minimize'},window.location.origin);}foundryBridge.status='Foundry potwierdziło działanie';}catch(err){foundryBridge.status=err.message;}finally{foundryBridge.busy=false;render();}
});
if(window.parent!==window&&/^https?:$/.test(location.protocol))window.parent.postMessage({protocol:'kult-gm-companion-v1',type:'connect'},location.origin);
render();
