let editorSection='map',materialFilter='available',historyFilter='play',importUndo=null;
const workspaceTabs=[['session','◉ Sesja'],['editor','◇ Edytor'],['pcs','♙ Postacie'],['npc','♟ NPC / duchy'],['clues','◈ Wiedza / przedmioty'],['timeline','◷ Historia sesji'],['save','⚙ Zapis / ustawienia']];
const materialGroups=[['available','Dostępne'],['played','Rozegrane'],['dismissed','Odrzucone']];
function statusGroup(x){return x.status==='played'?'played':x.status==='dismissed'?'dismissed':'available';}
function groupButtons(){return `<div class="row filter-row">${materialGroups.map(([id,label])=>`<button data-ui="material-filter" data-value="${id}" class="${materialFilter===id?'active':''}">${label}</button>`).join('')}</div>`;}
function world(){const labels={weather:'Pogoda',alarm:'Alarm',statue:'Posąg',harkness:'Harkness',illusion:'Iluzja'};return `<section class="panel"><div class="title-row"><h2>Stan świata</h2>${view==='session'?'':'<button data-custom="world-add">+ Pole</button>'}</div><div class="world-fields">${Object.entries(s().world).map(([key,value])=>`<div class="world-field"><div class="title-row"><label for="world-${esc(key)}">${esc(s().worldLabels?.[key]||labels[key]||key)}</label>${view==='session'?'':`<button class="small" data-custom="world-edit" data-world-key="${esc(key)}">Edytuj pole</button>`}</div><input id="world-${esc(key)}" data-world="${esc(key)}" value="${esc(value)}"></div>`).join('')}</div></section>`;}
function sessionMarkup(){const a=s(),l=loc(a.current),c=foundryBridge.catalog;
 const connected=[...new Set(a.links.filter(x=>x.includes(l.id)).map(x=>x.find(id=>id!==l.id)))].filter(id=>loc(id));
 const scenes=a.scenes.filter(x=>(x.location===l.id||x.location==='*')&&statusGroup(x)===materialFilter);
 return `<div class="title-row"><h1>Sesja</h1><div class="row"><span class="muted">Sesja ${a.session} · dzień ${a.day} · ${timeLabel(a)}</span><button data-ui="time">Zmień czas</button><button data-ui="next-session" class="small">Następna sesja</button></div></div><div class="session-grid"><section><div class="panel"><div class="title-row"><label>Aktualna lokacja<select data-action="location">${sel(a.locations.map(x=>[x.id,x.name]),l.id)}</select></label><button data-ui="prepare-location" class="small">Otwórz w edytorze</button></div><h2>${esc(l.name)}</h2><div class="player">${esc(l.player)}</div>${l.gm?`<details><summary>Wiedza MG</summary><div class="secret">${esc(l.gm)}</div></details>`:''}<div class="row location-tools">${b('Kopiuj opis','copy',l.id,'small')}${c?'<button data-fv="chat" class="small">Wyślij opis</button><button data-fv="handout" class="small">Handout</button>'+((foundryMapping()[l.id]||{}).journal?'<button data-fv="preview" class="small">Podgląd dziennika</button><button data-fv="journal" class="small">Pokaż dziennik</button>':''):''}</div>${connected.length?`<div class="routes"><label>Przejścia</label><div class="row">${connected.map(id=>b('→ '+loc(id).name,'move',id)).join('')}</div></div>`:''}</div><div class="panel"><div class="title-row"><h2>Sceny i wydarzenia</h2>${c?`<span class="tag">Aktywna: ${esc(c.scenes.find(x=>x.id===c.activeScene)?.name||'brak')}</span>`:''}</div>${groupButtons()}<h3>Sceny</h3><div class="cards">${scenes.map(x=>sceneCard(x,true)).join('')||empty('Brak scen w tej grupie.')}</div><h3 class="section-heading">Wydarzenia</h3>${eventList(a.events.filter(x=>(x.location===l.id||x.location==='*')&&statusGroup(x)===materialFilter))}</div><div class="panel"><h2>Wskazówki i przedmioty</h2>${knowledge(a.clues.filter(x=>x.location===l.id||x.location==='*'),a.items.filter(x=>x.location===l.id))}</div><div class="panel"><h2>Notatki sesji</h2><textarea id="quicknote" aria-label="Szybka notatka" placeholder="Decyzja graczy, pomysł, konsekwencja…"></textarea>${b('Dodaj notatkę','quick','','primary')}<div class="session-notes">${a.notes.filter(x=>x.location===l.id||x.location==='*').map(x=>`<details><summary>${esc(x.name)}</summary><p>${esc(x.gm)}</p></details>`).join('')}</div></div></section><section>${world()}${tracks()}${resources()}</section></div>`;
}
function timeLabel(a){return String(a.hour).padStart(2,'0')+':'+String(a.minute||0).padStart(2,'0');}
function timelineKind(x){if(x.kind)return x.kind;return /^(Zapisano|Utworzono|Przesunięto|Połączono|Usunięto|Cofnięto|Powiązano)/.test(x.text)?'edit':'play';}
function historyMarkup(){return `<div class="title-row"><h1>Historia sesji</h1>${b('+ Wpis','manual-log')}</div><div class="row filter-row"><button data-ui="history-filter" data-value="play" class="${historyFilter==='play'?'active':''}">Zdarzenia gry</button><button data-ui="history-filter" data-value="all" class="${historyFilter==='all'?'active':''}">Wszystkie zmiany</button></div><div class="panel timeline">${s().timeline.filter(x=>historyFilter==='all'||timelineKind(x)==='play').map(x=>`<article class="event"><label>Sesja ${x.session} · dzień ${x.day} · ${timeLabel(x)}</label><p>${esc(x.text)}</p></article>`).join('')||empty('Brak wpisów.')}</div>`;}
function editorMarkup(){let html=`<div class="title-row"><h1>Edytor scenariusza</h1></div><div class="row editor-tabs">${[['map','Lokacje i sceny'],['scenes','Wszystkie sceny'],['events','Wydarzenia'],['notes','Notatki'],['state','Stan / zasoby']].map(([id,name])=>`<button data-ui="editor-section" data-value="${id}" class="${editorSection===id?'active':''}">${name}</button>`).join('')}</div>`;
 if(editorSection==='map'){
  html+=graphMarkup();html=html.replace(/<p class="sub">.*?<\/p>/,'').replace(/<p class="map-caption">.*?<\/p>/,'');
 }else if(editorSection==='scenes'){html+=groupButtons()+`<div class="title-row"><h2>Sceny</h2>${b('+ Scena','add-scenes')}</div><div class="cards">${s().scenes.filter(x=>statusGroup(x)===materialFilter).map(x=>sceneCard(x)).join('')||empty('Brak scen.')}</div>`;}
 else if(editorSection==='state')html+=world()+tracks()+resources();
 return html;
}
function storageMarkup(){return `<section class="panel"><h2>Zapis</h2><p id="server-save-status">${esc(serverSave.status)}</p>${foundryBridge.catalog?serverSave.remote&&!serverSave.ready?'<p>Dostępne są dwie kopie. Wybierz, z którą chcesz pracować.</p><div class="row"><button data-storage="load" class="primary">Wczytaj z serwera</button><button data-storage="keep">Zapisz obecną kopię na serwerze</button></div>':serverSave.ready?'<p class="muted">Zmiany zapisują się automatycznie.</p><button data-storage="reload">Wczytaj zapis serwera</button>':'<button data-storage="retry">Sprawdź połączenie i zapis</button>':'<p class="muted">Zapis lokalny w tej przeglądarce.</p>'}</section>`;}
const oldStorageStatus=storageStatus;
storageStatus=function(text){oldStorageStatus(text);if(foundryBridge.catalog&&!serverSave.ready&&serverSave.remote&&view!=='save')$('#storageBadge').textContent='Wybierz kopię zapisu';};
const preparationRender=render;
render=function(){
 const target=view;if(target==='editor')view=editorSection==='events'?'events':editorSection==='notes'?'notes':'map';
 if(target==='save'||target==='timeline')view='settings';
 preparationRender();view=target;
 if(graphGesture&&target==='editor')return;
 if(target==='session')$('#content').innerHTML=sessionMarkup();
 if(target==='editor'){
  if(editorSection==='events'||editorSection==='notes'){const base=$('#content').innerHTML;$('#content').innerHTML=editorMarkup()+base;if(editorSection==='events'){const search=$('#search');const list=search?.nextElementSibling;if(list)list.innerHTML=groupButtons()+eventList(s().events.filter(x=>statusGroup(x)===materialFilter&&(x.name+' '+x.gm).toLowerCase().includes(query.toLowerCase())));}}
  else $('#content').innerHTML=editorMarkup();
 }
 if(target==='timeline')$('#content').innerHTML=historyMarkup();
 if(target==='save')$('#content').innerHTML=`<h1>Zapis i ustawienia</h1><div id="storage-tools">${storageMarkup()}</div><section class="panel"><h2>Kopie i import</h2><div class="row"><button data-ui="export">Pobierz kopię wszystkich danych</button><button data-ui="import">Importuj plik</button><button data-ui="undo-import" ${importUndo?'':'disabled'}>Cofnij ostatni import</button></div></section>${foundryPanel()}`;
 $('#nav').innerHTML=workspaceTabs.map(([id,name])=>b(name,'nav',id,id===view?'active':'')).join('');
 if(target==='session'&&foundryBridge.catalog){for(const button of document.querySelectorAll('[data-action="copy-clue"]')){const extra=document.createElement('button');extra.type='button';extra.className='small';extra.textContent='Wyślij wskazówkę';extra.dataset.fv='clue';extra.dataset.clue=button.dataset.id;button.after(extra);}}
 document.body.dataset.view=target;
 $('#storageBadge').textContent=foundryBridge.catalog?serverSave.remote&&!serverSave.ready?'Wybierz kopię zapisu':serverSave.status:'Zapis lokalny';
};
// Keep scene details in play mode, while creation and changes live in the editor.
const originalSceneCard=sceneCard;
sceneCard=function(scene,compact=false){let html=originalSceneCard(scene,compact).replace(/<button[^>]*data-custom="scene-status"[^>]*>.*?<\/button>/,`<select data-scene-state="${esc(scene.id)}" aria-label="Status sceny ${esc(scene.name)}">${sel([['available','Dostępna'],['active','W toku'],['played','Rozegrana'],['dismissed','Odrzucona']],scene.status)}</select>`);if(compact)html=html.replace(/<button[^>]*data-action="edit-scenes"[^>]*>.*?<\/button>/,'').replace(/<p class="source">.*?<\/p>/g,'').replace('</article>',`<details class="scene-description"><summary>Opis sceny</summary><div class="player">${esc(scene.player)}</div><div class="secret">${esc(scene.gm)}</div></details></article>`);return html;};
function openTimeEditor(){const a=s(),d=$('#editor');d.innerHTML=`<form id="timeform"><h2>Czas w grze</h2><label>Dzień<input name="day" type="number" min="1" step="1" value="${a.day}" required></label><label>Godzina<input name="time" type="time" value="${timeLabel(a)}" required></label><div class="row">${[15,30,60,180].map(m=>`<button type="button" data-ui="advance-time" data-value="${m}">+ ${m===60?'1 godz.':m===180?'3 godz.':m+' min'}</button>`).join('')}</div><div class="row"><button class="primary">Ustaw czas</button><button type="button" data-action="close">Anuluj</button></div></form>`;d.showModal();$('#timeform').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),[h,m]=f.get('time').split(':').map(Number),day=Number(f.get('day'));if(!Number.isInteger(day)||day<1)return;a.day=day;a.hour=h;a.minute=m;d.close();changed('Ustawiono czas: dzień '+day+', '+timeLabel(a),'play');};}
function advanceTime(minutes){const a=s(),total=a.hour*60+(a.minute||0)+minutes;a.day+=Math.floor(total/1440);a.hour=Math.floor(total%1440/60);a.minute=total%60;$('#editor').close();changed('Upłynęło '+minutes+' min · '+timeLabel(a),'play');}
function mergeImport(current,incoming){const result=structuredClone(current);for(const a of incoming.scenarios){const imported=structuredClone(a);if(result.scenarios.some(x=>x.id===imported.id)){imported.id=uid();imported.name+=' · import';}result.scenarios.push(imported);}return validateDB(result);}
$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10000000)throw Error('Plik za duży');const incoming=validateDB(JSON.parse(await f.text()));const choice=await askDialog('Plik zawiera '+incoming.scenarios.length+' scenariuszy. Jak je wczytać?',{choices:[['add','Dodaj scenariusze'],['replace','Zastąp wszystkie dane'],['cancel','Anuluj']]});if(!choice)return;if(choice==='replace'&&!await uiConfirm('Zastąpić wszystkie scenariusze? Poprzednią kopię można cofnąć do zamknięcia panelu.'))return;importUndo=structuredClone(db);cancelGraphGesture();db=choice==='add'?mergeImport(db,incoming):incoming;view='save';persist();render();notify('Import zakończony. Możesz go cofnąć w panelu Zapis.');}catch(err){notify('Nie można zaimportować: '+err.message);}finally{e.target.value='';}};
$('#storageBadge').onclick=()=>{view='save';render();};
document.addEventListener('click',async e=>{const btn=e.target.closest('[data-ui]');if(!btn)return;const action=btn.dataset.ui,value=btn.dataset.value;
 if(action==='editor-section'){editorSection=value;view='editor';query='';render();}
 if(action==='prepare-location'){editorSection='map';view='editor';render();}
 if(action==='material-filter'){materialFilter=value;render();}
 if(action==='history-filter'){historyFilter=value;render();}
 if(action==='time')openTimeEditor();if(action==='advance-time')advanceTime(Number(value));
 if(action==='next-session'){const a=s();a.session++;changed('Początek sesji '+a.session,'play');}
 if(action==='export')exportDB();if(action==='import')$('#file').click();
 if(action==='undo-import'&&importUndo&&await uiConfirm('Cofnąć ostatni import i przywrócić poprzednie dane?')){cancelGraphGesture();db=importUndo;importUndo=null;persist();render();}
});
// New scenarios open in preparation mode.
const createScenario=$('#newScenario').onclick;$('#newScenario').onclick=async()=>{const before=db.scenarios.length;await createScenario();if(db.scenarios.length>before){view='editor';editorSection='map';render();}};
render();

foundryPanel=function(){const c=foundryBridge.catalog,m=foundryMapping()[s().current]||{};return `<section class="panel" id="foundry-panel"><h2>Foundry VTT</h2>${c?`<p class="muted">Aktywna scena: ${esc(c.scenes.find(x=>x.id===c.activeScene)?.name||'brak')}</p><label>Dziennik aktualnej lokacji<select data-custom-journal>${sel([['','Bez powiązania'],...c.journals.map(x=>[x.id,x.name])],m.journal||'')}</select></label><div class="row"><button data-fv="preview" ${m.journal?'':'disabled'}>Podgląd dziennika MG</button><button data-fv="journal" ${m.journal?'':'disabled'}>Pokaż dziennik graczom</button><button data-fv="refresh">Odśwież listę</button></div>`:'<p class="muted">Tryb lokalny</p>'}</section>`;};
document.addEventListener('change',e=>{const id=e.target.dataset.sceneState;if(!id)return;const scene=s().scenes.find(x=>x.id===id);if(!scene)return;scene.status=e.target.value;changed('Scena: '+scene.name+' · '+e.target.options[e.target.selectedIndex].text,'play');});
render();

const locationGraphMarkup=graphMarkup;
graphMarkup=function(){return locationGraphMarkup().replace(/<article class="card">[\s\S]*?<\/article>/g,card=>{const id=card.match(/data-location="([^"]+)"/)?.[1];if(!id)return card;const list=s().scenes.filter(x=>x.location===id);return card.replace('</article>',`<details class="location-scene-group"><summary>Sceny (${list.length})</summary><div class="list">${list.map(x=>sceneCard(x)).join('')||'<p class="muted">Brak scen.</p>'}</div></details></article>`);});};
render();
